name: Deploy Chrome Extension 

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install chrome-webstore-upload-cli
        run: npm install -g chrome-webstore-upload-cli

      - name: Build project
        run: npm run build

      # 압축 전에 dist/ 폴더 구조 확인(디버깅용)
      - name: List dist directory contents
        run: ls -al dist/

      - name: Check manifest.json
        run: |
          if [ ! -f "dist/manifest.json" ]; then 
            echo "manifest.json not found in dist/"; 
            exit 1; 
          fi

      - name: Build extension
        run: cd dist && zip -r ../my-extension.zip .

      # 압축된 파일 내부 구조 확인(디버깅용)
      - name: List contents of my-extension.zip
        run: unzip -l my-extension.zip

      - name: Upload and publish to Chrome Web Store
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: |
          echo '{
            "extensionId": "'"$EXTENSION_ID"'",
            "clientId": "'"$CLIENT_ID"'",
            "clientSecret": "'"$CLIENT_SECRET"'",
            "refreshToken": "'"$REFRESH_TOKEN"'"
          }' > chrome-webstore-auth.json

          cd dist
          chrome-webstore-upload upload --source my-extension.zip && chrome-webstore-upload publish
